/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package decide;

import decide.launch.Launch;
import decide.launch.LaunchInput;
import decide.launch.LaunchOutput;

public class App {
    
    public static void main(String[] args) {
        LaunchInput input = new LaunchInput(null, null, null, null);   // temp value
        LaunchOutput output = Launch.decide(input);
    }
}
